name: Deploy to QA Server

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: qa-runner

    steps:
      - name: Stop IIS Website QA KKDD
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe stop site /site.name:'KKDD_qa_auto'" -Verb RunAs

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull git code
        run: |
            git pull origin qa

      - name: Restore dependencies
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet restore

      - name: publish dotnet
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish --no-restore -c Release -o ./publish
      - name: Copy to run folder
        shell: powershell
        run: |
          if (Test-Path "C:\inetpub\wwwroot\KKDD_qa_auto") {
              Remove-Item -Recurse -Force "C:\inetpub\wwwroot\KKDD_qa_auto"
          }
          Copy-Item -Path ".\publish" -Destination "C:\inetpub\wwwroot\KKDD_qa_auto" -Recurse
      - name: start IIS Website
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe start site /site.name:'KKDD_qa_auto'" -Verb RunAs
