name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai
            git pull origin main
            cd "$env:WINDIR\system32\inetsrv"
            appcmd stop site /site.name:"KiemKeDatDai_auto"
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish
            cd %windir%\system32\inetsrv
            appcmd start site /site.name:"KiemKeDatDai_auto"
