name: Deploy to QA Server

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: qa-runner

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull git code
        run: |
            git pull origin qa

      - name: Restore dependencies
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet restore
      - name: Stop IIS Website QA KKDD
        run: |
            %windir%\system32\inetsrv\appcmd stop site /site.name:"KKDD_qa_auto"
        shell: cmd
      - name: publish dotnet
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish --no-restore -c Release -o C:\githubrunner\KKDD_qa_auto
      - name: start IIS Website
        run: |
            %windir%\system32\inetsrv\appcmd start site /site.name:"KKDD_qa_auto"
        shell: cmd