name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir %USERPROFILE%\.ssh
          echo %SSH_PRIVATE_KEY% > %USERPROFILE%\.ssh\id_rsa
          chmod 600 %USERPROFILE%\.ssh\id_rsa
          ssh-keyscan -H %SERVER_IP% >> %USERPROFILE%\.ssh\known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd C:\inetpub\wwwroot\
            git pull origin main
          EOF
