name: Deploy to QA Server

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: qa-runner

    steps:
      - name: Stop IIS Website QA KKDD
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe stop site /site.name:'KKDD_qa_auto'" -Verb RunAs

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull git code
        run: |
            git pull origin qa
      - name: Update database
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.EntityFrameworkCore

            dotnet ef database update --connection "Server=WIN-S1IBJB84OOO\SQL2022; Database=KiemKeDatDai; Trusted_Connection=True; TrustServerCertificate=True; uid=sa; password=DataTK@2025KKK$123BCD569;"

      - name: Restore dependencies
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet restore

      - name: publish dotnet
        run: |
            cd C:\githubrunner\_work\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish --no-restore

      - name: start IIS Website
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe start site /site.name:'KKDD_qa_auto'" -Verb RunAs
