name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai
            git pull origin main
      - name: Stop IIS Website
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe stop site /site.name:'KiemKeDatDai_auto'" -Verb RunAs
      - name: publish dotnet
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish
      - name: start IIS Website
        run: |
            cd %windir%\system32\inetsrv
            appcmd start site /site.name:"KiemKeDatDai_auto"
