name: Deploy to Server

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Allow git directory ownership
        run: |
            git config --global --add safe.directory "C:\services\KiemKeDatDai_QA\KiemKeDatDai"

      - name: Pull git code
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai
            git pull origin release

      - name: Stop IIS Website product
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe stop site /site.name:'KiemKeDatDai_auto'" -Verb RunAs

      - name: Restore dependencies
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet restore

      - name: publish dotnet
        run: |
            cd C:\inetpub\wwwroot\KiemKeDatDai\KiemKeDatDai\aspnet-core\src\KiemKeDatDai.Web.Host
            dotnet publish --no-restore
            
      - name: start IIS Website
        run: |
            Start-Process powershell -ArgumentList "cd C:\Windows\System32\inetsrv; .\appcmd.exe start site /site.name:'KiemKeDatDai_auto'" -Verb RunAs
