import LoadableComponent from './../Loadable/index';
import { HomeOutlined, UserOutlined, TagsOutlined, AppstoreOutlined, InfoCircleOutlined } from '@ant-design/icons';

export const ROUTER_PATH = {
  HOME: "/home",
  REPORT: "/report",
  ROLES: "/roles",
  USERS: "/users",
  CAPDVHC: "/capdvhc",
  KYKIEMKE: "/ky-thong-ke-kiem-ke",
  CAUHINH: "/cauhinh",
  DONVIHANHCHINH: "/don-vi-hanh-chinh",
  NEWS: "/tin-tuc",
  CHANGEPASSWORD: "/change-password",
  YKIEN: "/y-kien",

}

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'Đăng nhập',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: ROUTER_PATH.HOME,
    exact: true,
    name: 'homePage',
    permission: '',
    title: 'Trang chủ',
    component: LoadableComponent(() => import('../../scenes/Home/homePage')),
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: ROUTER_PATH.USERS,
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/Users')),
  },
  {
    path: ROUTER_PATH.ROLES,
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/Roles')),
  },
  {
    path: ROUTER_PATH.CAPDVHC,
    permission: 'Pages.Roles',
    title: 'Cấp đơn vị hành chính',
    name: 'capdvhc',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/CapDonViHanhChinh')),
  },
  {
    path: ROUTER_PATH.DONVIHANHCHINH,
    permission: 'Pages.Roles',
    title: 'Đơn vị hành chính',
    name: 'dvhc',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/DonViHanhChinh')),
  },
  {
    path: ROUTER_PATH.KYKIEMKE,
    permission: 'Pages.Roles',
    title: 'Kỳ thống kê kiểm kê',
    name: 'kykiemke',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/KyKiemKe')),
  },
  {
    path: ROUTER_PATH.CAUHINH,
    permission: 'Pages.Roles',
    title: 'Cấu hình hệ thống',
    name: 'cauhinh',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/CauHinhHeThong')),
  },
  {
    path: ROUTER_PATH.NEWS,
    permission: 'Pages.Roles',
    title: 'Cấu hình tin tức',
    name: 'cauhinh',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/News')),
  },
  {
    path: ROUTER_PATH.YKIEN,
    permission: 'Pages.Roles',
    title: 'Ý kiến người dùng',
    name: 'ykien',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Admin/YKienNguoiDung')),
  },
  {
    path: ROUTER_PATH.CHANGEPASSWORD,
    title: 'Đổi mật khẩu',
    name: 'changePassword',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/ChangePassword')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: AppstoreOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/about',
    permission: '',
    title: 'About',
    name: 'about',
    icon: InfoCircleOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/About')),
  },
  {
    path: '/report/:reportInfo',
    permission: '',
    title: 'Report',
    name: 'report',
    icon: InfoCircleOutlined,
    hiddenHeader: true,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/BieuMauPage/bieuMauPage')),
  },
  {
    path: ROUTER_PATH.REPORT,
    permission: '',
    title: 'Báo cáo số liệu',
    name: 'report',
    icon: InfoCircleOutlined,
    hiddenHeader: true,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/BaoCaoSoLieu')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
];

export const routers = [...userRouter, ...appRouters];
